import type { SqlStatementManifestEntry } from '@upi-spend-tracker/shared-utils';

export const serverDatabaseExpectedTables = [
  'schema_migrations',
  'schema_metadata',
  'users',
  'devices',
  'refresh_tokens',
  'device_pairing_codes',
  'categories',
  'merchants',
  'merchant_aliases',
  'transactions',
  'transaction_items',
  'rules',
  'budgets',
  'budget_scopes',
  'sync_cursors',
  'audit_events',
] as const;

export const serverDatabaseMigrations = [
  {
    id: '0001_initial_server_schema',
    statements: [
      `CREATE TABLE IF NOT EXISTS users (
        id TEXT PRIMARY KEY,
        mode TEXT NOT NULL DEFAULT 'guest',
        locale TEXT,
        timezone TEXT NOT NULL DEFAULT 'UTC',
        record_version INTEGER NOT NULL DEFAULT 1,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        deleted_at TIMESTAMPTZ
      );`,
      `CREATE TABLE IF NOT EXISTS devices (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        platform TEXT NOT NULL,
        device_name TEXT,
        runtime_version TEXT,
        push_token TEXT,
        last_seen_at TIMESTAMPTZ,
        record_version INTEGER NOT NULL DEFAULT 1,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        deleted_at TIMESTAMPTZ
      );`,
      `CREATE TABLE IF NOT EXISTS refresh_tokens (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        device_id TEXT REFERENCES devices(id) ON DELETE SET NULL,
        token_hash TEXT NOT NULL UNIQUE,
        expires_at TIMESTAMPTZ NOT NULL,
        revoked_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );`,
      `CREATE TABLE IF NOT EXISTS device_pairing_codes (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        code_hash TEXT NOT NULL UNIQUE,
        expires_at TIMESTAMPTZ NOT NULL,
        consumed_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );`,
      `CREATE TABLE IF NOT EXISTS categories (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        slug TEXT NOT NULL,
        name TEXT NOT NULL,
        kind TEXT NOT NULL,
        sort_order INTEGER NOT NULL DEFAULT 0,
        record_version INTEGER NOT NULL DEFAULT 1,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        deleted_at TIMESTAMPTZ,
        UNIQUE (user_id, slug)
      );`,
      `CREATE TABLE IF NOT EXISTS merchants (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        normalized_name TEXT NOT NULL,
        display_name TEXT NOT NULL,
        source TEXT NOT NULL DEFAULT 'user',
        record_version INTEGER NOT NULL DEFAULT 1,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        deleted_at TIMESTAMPTZ,
        UNIQUE (user_id, normalized_name)
      );`,
      `CREATE TABLE IF NOT EXISTS merchant_aliases (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        merchant_id TEXT NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,
        alias_raw TEXT NOT NULL,
        alias_normalized TEXT NOT NULL,
        source TEXT NOT NULL DEFAULT 'user',
        record_version INTEGER NOT NULL DEFAULT 1,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        deleted_at TIMESTAMPTZ,
        UNIQUE (user_id, alias_normalized)
      );`,
      `CREATE TABLE IF NOT EXISTS transactions (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        merchant_id TEXT REFERENCES merchants(id) ON DELETE SET NULL,
        source_app TEXT,
        status TEXT NOT NULL,
        currency_code TEXT NOT NULL DEFAULT 'INR',
        total_minor BIGINT NOT NULL,
        remainder_minor BIGINT NOT NULL DEFAULT 0,
        remainder_type TEXT,
        paid_at TIMESTAMPTZ NOT NULL,
        captured_at TIMESTAMPTZ,
        raw_merchant TEXT,
        parser_version TEXT,
        parser_confidence DOUBLE PRECISION,
        note TEXT,
        record_version INTEGER NOT NULL DEFAULT 1,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        deleted_at TIMESTAMPTZ
      );`,
      `CREATE TABLE IF NOT EXISTS transaction_items (
        id TEXT PRIMARY KEY,
        transaction_id TEXT NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
        category_id TEXT REFERENCES categories(id) ON DELETE SET NULL,
        merchant_id TEXT REFERENCES merchants(id) ON DELETE SET NULL,
        name TEXT NOT NULL,
        quantity INTEGER NOT NULL DEFAULT 1,
        line_total_minor BIGINT NOT NULL,
        sort_order INTEGER NOT NULL DEFAULT 0,
        note TEXT,
        record_version INTEGER NOT NULL DEFAULT 1,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        deleted_at TIMESTAMPTZ
      );`,
      `CREATE TABLE IF NOT EXISTS rules (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        scope_type TEXT NOT NULL,
        match_json JSONB NOT NULL,
        outcome_json JSONB NOT NULL,
        is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
        priority INTEGER NOT NULL DEFAULT 0,
        record_version INTEGER NOT NULL DEFAULT 1,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        deleted_at TIMESTAMPTZ
      );`,
      `CREATE TABLE IF NOT EXISTS budgets (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        scope_type TEXT NOT NULL,
        amount_minor BIGINT NOT NULL,
        cycle_type TEXT NOT NULL,
        anchor_day INTEGER,
        timezone TEXT NOT NULL DEFAULT 'UTC',
        threshold_json JSONB NOT NULL DEFAULT '[]'::jsonb,
        is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
        record_version INTEGER NOT NULL DEFAULT 1,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        deleted_at TIMESTAMPTZ
      );`,
      `CREATE TABLE IF NOT EXISTS budget_scopes (
        id TEXT PRIMARY KEY,
        budget_id TEXT NOT NULL REFERENCES budgets(id) ON DELETE CASCADE,
        entity_type TEXT NOT NULL,
        entity_id TEXT NOT NULL,
        record_version INTEGER NOT NULL DEFAULT 1,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        deleted_at TIMESTAMPTZ
      );`,
      `CREATE TABLE IF NOT EXISTS sync_cursors (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        device_id TEXT REFERENCES devices(id) ON DELETE SET NULL,
        cursor_value TEXT NOT NULL,
        record_version INTEGER NOT NULL DEFAULT 1,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );`,
      `CREATE TABLE IF NOT EXISTS audit_events (
        id TEXT PRIMARY KEY,
        user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
        entity_type TEXT NOT NULL,
        entity_id TEXT NOT NULL,
        action TEXT NOT NULL,
        actor TEXT NOT NULL,
        payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );`,
      'CREATE INDEX IF NOT EXISTS devices_user_id_idx ON devices (user_id);',
      'CREATE INDEX IF NOT EXISTS categories_user_id_slug_idx ON categories (user_id, slug);',
      'CREATE INDEX IF NOT EXISTS merchants_user_id_normalized_name_idx ON merchants (user_id, normalized_name);',
      'CREATE INDEX IF NOT EXISTS merchant_aliases_merchant_id_idx ON merchant_aliases (merchant_id);',
      'CREATE INDEX IF NOT EXISTS transactions_user_id_paid_at_idx ON transactions (user_id, paid_at DESC);',
      'CREATE INDEX IF NOT EXISTS transactions_status_idx ON transactions (status);',
      'CREATE INDEX IF NOT EXISTS transaction_items_transaction_id_idx ON transaction_items (transaction_id);',
      'CREATE INDEX IF NOT EXISTS rules_user_id_priority_idx ON rules (user_id, priority DESC);',
      'CREATE INDEX IF NOT EXISTS budgets_user_id_cycle_type_idx ON budgets (user_id, cycle_type);',
      'CREATE INDEX IF NOT EXISTS sync_cursors_user_id_idx ON sync_cursors (user_id);',
    ],
  },
] as const satisfies readonly SqlStatementManifestEntry[];
